agrics/agrics/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
    path('', include('agrictimes.urls', namespace='agrictimes')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

agrics/agrictimes/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name ='agrictimes'

urlpatterns = [
    path('',views.product_list, name='product_list'),
    path('<slug:category_slug>/',views.product_list, name ='product_list_by_category'),
    path('<int:id>/<slug:slug>/',views.product_detail, name='product_detail'),
    #path('login/', views.user_login, name='login'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

]

agrics/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

agrics/agrictimes/models.py
from django.db import models
from django.urls import reverse
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug =models.SlugField(max_length=200, unique=True)
    
    class Meta:
        ordering = ('name',)
        verbose_name ='category'
        verbose_name_plural ='categories'
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('agrictimes:product_list_by_category', args=[self.slug])
    
class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)
        
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('agrictimes:product_detail',args=[self.id, self.slug])

agrics/agrictimes/views.py
from django.contrib import auth
from django.shortcuts import render
from .models import Product, Category
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage,PageNotAnInteger
from django.shortcuts import get_object_or_404

from django.contrib.auth.decorators import login_required


# Create your views here.



def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
            category = get_object_or_404(Category,slug=category_slug)
            products = products.filter(category=category)
    paginator = Paginator(products, 2)
    page = request.GET.get('page')
    print(page)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
    # If page is not an integer deliver the first page
            products = paginator.page(1)
    except EmptyPage:
    # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)

    return render(request,'products/product_list.html', {'category':category,'categories':categories,'products':products,'page':page})


@login_required(login_url='/dashboard/login/')

def product_detail(request,id,slug):
    product = get_object_or_404(Product,id=id,slug=slug,available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'products/product_detail.html',{'product':product,'cart_product_form':cart_product_form,})

agrics/agrictimes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
 <head>
    <meta charset="utf-8" />
    <title>{% block title %}My shop{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
 </head>
 <body>
    <div id="header">
    <a href="/" class="logo">My shop</a>
    {% if messages %}
 <ul class="messages">
 {% for message in messages %}
 <li class="{{ message.tags }}">
 {{ message|safe }}
 <a href="#" class="close">x</a>
 </li>
 {% endfor %}
 </ul>
{% endif %}
    </div>
    <div id="subheader">
      <div class="cart">
         {% with total_items=cart|length %}
         {% if total_items > 0 %}
         Your cart:
         <a href="{% url "cart:cart_detail" %}">
         {{ total_items }} item{{ total_items|pluralize }},
         ${{ cart.get_total_price }}
         </a>
         {% else %}
         Your cart is empty.
         {% endif %}
         {% endwith %}
      </div>
    </div>
    
    <div id="content">
    {% block content %}
    {% endblock %}
    </div>
    <span class="user">
      {% if request.user.is_authenticated %}
         Hello {{ request.user.username }},

         <a href="{% url "dashboard:logout" %}?next=/">Logout</a>
      {% else %}
         <a href="{% url "dashboard:login" %}">Log-in</a>
      {% endif %}
      </span>
 </body>
</html>

agrics/agrictimes/templates/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
   </div>